openapi: 3.0.0
info:
  title: Social App
  description: Social App - LCO - DOC - AAVEG
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: Local host version of social app
  - url: http://dummy/api/v1
    description: dummy version of social app

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
